table resultater

	measure 'Valgt perspektiv' = SELECTEDVALUE ( Svartidsperspektiv[Perspektiv], "Enhetstid" )

	measure 'Antall resultater' = COUNTROWS ( resultater )
		formatString: #,0

	measure 'Median pasientforløp dager' = MEDIAN ( resultater[Svartid pasient dager] )
		formatString: 0.0

	measure 'Median seksjonstid dager' = MEDIAN ( resultater[Svartid seksjon dager] )
		formatString: 0.0

	measure 'Median enhetstid dager' = MEDIAN ( resultater[Svartid enhet dager] )
		formatString: 0.0

	measure 'Antall gyldige svartider' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SWITCH (
					Perspektiv,
					"Pasientforløp", COUNT ( resultater[Svartid pasient dager] ),
					"Seksjonstid", COUNT ( resultater[Svartid seksjon dager] ),
					COUNT ( resultater[Svartid enhet dager] )
				)
		formatString: #,0

	measure 'Median svartid dager' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SWITCH (
					Perspektiv,
					"Pasientforløp", MEDIAN ( resultater[Svartid pasient dager] ),
					"Seksjonstid", MEDIAN ( resultater[Svartid seksjon dager] ),
					MEDIAN ( resultater[Svartid enhet dager] )
				)
		formatString: 0.0

	measure 'Gjennomsnitt svartid dager' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SWITCH (
					Perspektiv,
					"Pasientforløp", AVERAGE ( resultater[Svartid pasient dager] ),
					"Seksjonstid", AVERAGE ( resultater[Svartid seksjon dager] ),
					AVERAGE ( resultater[Svartid enhet dager] )
				)
		formatString: 0.0

	measure 'P75 svartid dager' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SWITCH (
					Perspektiv,
					"Pasientforløp", PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid pasient dager] ) ), resultater[Svartid pasient dager], 0.75 ),
					"Seksjonstid", PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid seksjon dager] ) ), resultater[Svartid seksjon dager], 0.75 ),
					PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid enhet dager] ) ), resultater[Svartid enhet dager], 0.75 )
				)
		formatString: 0.0

	measure 'P90 svartid dager' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SWITCH (
					Perspektiv,
					"Pasientforløp", PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid pasient dager] ) ), resultater[Svartid pasient dager], 0.90 ),
					"Seksjonstid", PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid seksjon dager] ) ), resultater[Svartid seksjon dager], 0.90 ),
					PERCENTILEX.INC ( FILTER ( resultater, NOT ISBLANK ( resultater[Svartid enhet dager] ) ), resultater[Svartid enhet dager], 0.90 )
				)
		formatString: 0.0

	measure 'Antall innen individuell frist' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SUMX (
					resultater,
					VAR Varighet = SWITCH ( Perspektiv, "Pasientforløp", resultater[Svartid pasient dager], "Seksjonstid", resultater[Svartid seksjon dager], resultater[Svartid enhet dager] )
					RETURN IF ( NOT ISBLANK ( Varighet ) && NOT ISBLANK ( resultater[Svarfrist] ) && Varighet <= resultater[Svarfrist], 1, 0 )
				)
		formatString: #,0

	measure 'Antall over individuell frist' =
			VAR Perspektiv = [Valgt perspektiv]
			RETURN
				SUMX (
					resultater,
					VAR Varighet = SWITCH ( Perspektiv, "Pasientforløp", resultater[Svartid pasient dager], "Seksjonstid", resultater[Svartid seksjon dager], resultater[Svartid enhet dager] )
					RETURN IF ( NOT ISBLANK ( Varighet ) && NOT ISBLANK ( resultater[Svarfrist] ) && Varighet > resultater[Svarfrist], 1, 0 )
				)
		formatString: #,0

	measure 'Andel innen individuell frist' = DIVIDE ( [Antall innen individuell frist], [Antall innen individuell frist] + [Antall over individuell frist] )
		formatString: 0.0%

	measure 'Antall ekskludert datakvalitet' = COUNTROWS ( resultater ) - [Antall gyldige svartider]
		formatString: #,0

	measure 'Andel ekskludert datakvalitet' = DIVIDE ( [Antall ekskludert datakvalitet], COUNTROWS ( resultater ) )
		formatString: 0.0%

	measure 'Entydig svarfrist dager' = SELECTEDVALUE ( resultater[Svarfrist] )
		formatString: 0

	measure 'Godkjenningsetterslep median dager' = MEDIAN ( resultater[Godkjenningsetterslep dager] )
		formatString: 0.0

	measure 'Datakvalitet OK' = CALCULATE ( COUNTROWS ( resultater ), resultater[Datakvalitet status] = "OK" )
		formatString: #,0

	measure 'Datakvalitet avvik' = COUNTROWS ( resultater ) - [Datakvalitet OK]
		formatString: #,0

	measure 'Svartid status tekst' =
			VAR Andel = [Andel innen individuell frist]
			RETURN SWITCH ( TRUE (), ISBLANK ( Andel ), "Ingen gyldige observasjoner", Andel >= 0.90, "På mål", Andel >= 0.75, "Følg med", "Krever oppfølging" )

	measure 'Svartid status farge' =
			VAR Andel = [Andel innen individuell frist]
			RETURN SWITCH ( TRUE (), ISBLANK ( Andel ), "#64748B", Andel >= 0.90, "#0F766E", Andel >= 0.75, "#B45309", "#B42318" )

	measure 'Fireukers glidende volum' = DIVIDE ( CALCULATE ( [Antall analyser], DATESINPERIOD ( Dato[Date], MAX ( Dato[Date] ), -28, DAY ) ), 4 )
		formatString: #,0

	measure 'Lavvolumgrense P10' = PERCENTILEX.INC ( ALLSELECTED ( Dato[ÅrUke] ), CALCULATE ( [Antall analyser] ), 0.10 )
		formatString: #,0

	column Materiale
		dataType: string
		summarizeBy: none
		sourceColumn: Materiale

	column Analyse
		dataType: string
		summarizeBy: none
		sourceColumn: Analyse

	column Nukleinsyre
		dataType: string
		summarizeBy: none
		sourceColumn: Nukleinsyre

	column Rapportgruppe
		dataType: string
		summarizeBy: none
		sourceColumn: Rapportgruppe

	column 'Tidspunkt.prøvetaking'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Tidspunkt.prøvetaking

	column 'Tidspunkt.opprettet'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Tidspunkt.opprettet

	column 'Tidspunkt.analysebestilling'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Tidspunkt.analysebestilling

	column 'Tidspunkt.analyseresultat'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Tidspunkt.analyseresultat

	column 'Tidspunkt.godkjenning'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Tidspunkt.godkjenning

	column 'Ekstraksjon.analysebestilling'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Ekstraksjon.analysebestilling

	column 'Ekstraksjon.ferdig'
		dataType: dateTime
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none
		sourceColumn: Ekstraksjon.ferdig

	column Svarfrist
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: Svarfrist

	column 'Prøvetaking dato' = IF ( ISBLANK ( resultater[Tidspunkt.prøvetaking] ), BLANK (), DATE ( YEAR ( resultater[Tidspunkt.prøvetaking] ), MONTH ( resultater[Tidspunkt.prøvetaking] ), DAY ( resultater[Tidspunkt.prøvetaking] ) ) )
		formatString: dd.MM.yyyy
		summarizeBy: none

	column 'Analysebestilling dato' = IF ( ISBLANK ( resultater[Tidspunkt.analysebestilling] ), BLANK (), DATE ( YEAR ( resultater[Tidspunkt.analysebestilling] ), MONTH ( resultater[Tidspunkt.analysebestilling] ), DAY ( resultater[Tidspunkt.analysebestilling] ) ) )
		formatString: dd.MM.yyyy
		summarizeBy: none

	column 'Analyseresultat dato' = IF ( ISBLANK ( resultater[Tidspunkt.analyseresultat] ), BLANK (), DATE ( YEAR ( resultater[Tidspunkt.analyseresultat] ), MONTH ( resultater[Tidspunkt.analyseresultat] ), DAY ( resultater[Tidspunkt.analyseresultat] ) ) )
		formatString: dd.MM.yyyy
		summarizeBy: none

	column 'Godkjenning dato' = IF ( ISBLANK ( resultater[Tidspunkt.godkjenning] ), BLANK (), DATE ( YEAR ( resultater[Tidspunkt.godkjenning] ), MONTH ( resultater[Tidspunkt.godkjenning] ), DAY ( resultater[Tidspunkt.godkjenning] ) ) )
		formatString: dd.MM.yyyy
		summarizeBy: none

	column 'Enhet starttid' =
			VAR Bestilling = resultater[Tidspunkt.analysebestilling]
			VAR Ekstraksjon = resultater[Ekstraksjon.ferdig]
			RETURN SWITCH ( TRUE (), ISBLANK ( Bestilling ), Ekstraksjon, ISBLANK ( Ekstraksjon ), Bestilling, Bestilling >= Ekstraksjon, Bestilling, Ekstraksjon )
		formatString: dd.MM.yyyy HH:mm
		summarizeBy: none

	column 'Enhet startkilde' =
			VAR Bestilling = resultater[Tidspunkt.analysebestilling]
			VAR Ekstraksjon = resultater[Ekstraksjon.ferdig]
			RETURN SWITCH ( TRUE (), ISBLANK ( Bestilling ) && ISBLANK ( Ekstraksjon ), "Mangler start", ISBLANK ( Ekstraksjon ), "Analysebestilling", ISBLANK ( Bestilling ), "Ekstraksjon ferdig", Bestilling >= Ekstraksjon, "Analysebestilling (senest)", "Ekstraksjon ferdig (senest)" )
		summarizeBy: none

	column 'Svartid pasient dager' =
			VAR Starttid = resultater[Tidspunkt.prøvetaking]
			VAR Sluttid = resultater[Tidspunkt.analyseresultat]
			VAR varighet = Sluttid - Starttid
			RETURN IF ( ISBLANK ( Starttid ) || ISBLANK ( Sluttid ) || varighet < 0 || varighet > 365, BLANK (), varighet )
		formatString: 0.0
		summarizeBy: none

	column 'Svartid seksjon dager' =
			VAR Starttid = resultater[Tidspunkt.analysebestilling]
			VAR Sluttid = resultater[Tidspunkt.analyseresultat]
			VAR varighet = Sluttid - Starttid
			RETURN IF ( ISBLANK ( Starttid ) || ISBLANK ( Sluttid ) || varighet < 0 || varighet > 365, BLANK (), varighet )
		formatString: 0.0
		summarizeBy: none

	column 'Svartid enhet dager' =
			VAR Starttid = resultater[Enhet starttid]
			VAR Sluttid = resultater[Tidspunkt.analyseresultat]
			VAR varighet = Sluttid - Starttid
			RETURN IF ( ISBLANK ( Starttid ) || ISBLANK ( Sluttid ) || varighet < 0 || varighet > 365, BLANK (), varighet )
		formatString: 0.0
		summarizeBy: none

	column 'Godkjenningsetterslep dager' =
			VAR Starttid = resultater[Tidspunkt.analyseresultat]
			VAR Sluttid = resultater[Tidspunkt.godkjenning]
			VAR varighet = Sluttid - Starttid
			RETURN IF ( ISBLANK ( Starttid ) || ISBLANK ( Sluttid ) || varighet < 0 || varighet > 365, BLANK (), varighet )
		formatString: 0.0
		summarizeBy: none

	column 'Datakvalitet status' =
			VAR Resultat = resultater[Tidspunkt.analyseresultat]
			VAR Prøve = resultater[Tidspunkt.prøvetaking]
			VAR Bestilling = resultater[Tidspunkt.analysebestilling]
			VAR EnhetStart = resultater[Enhet starttid]
			VAR Godkjenning = resultater[Tidspunkt.godkjenning]
			RETURN
				SWITCH (
					TRUE (),
					ISBLANK ( Resultat ), "Mangler sluttid",
					ISBLANK ( Prøve ), "Mangler prøvetaking",
					Prøve > Resultat, "Negativ analysetid - sjekk data",
					Resultat - Prøve > 365, "Ekstrem prøvetakingsdato",
					ISBLANK ( Bestilling ), "Mangler analysebestilling",
					Bestilling > Resultat, "Negativ analysetid - sjekk data",
					ISBLANK ( EnhetStart ), "Mangler enhetsstart",
					EnhetStart > Resultat, "Negativ analysetid - sjekk data",
					NOT ISBLANK ( Godkjenning ) && Godkjenning < Resultat, "Godkjenning før analyseresultat",
					ISBLANK ( resultater[Svarfrist] ), "Mangler svarfrist",
					"OK"
				)
		summarizeBy: none

	partition resultater = m
		mode: import
		source =
				let
				    Kilde =
				        Csv.Document(
				            Web.Contents(
				                "https://hsorhf.sharepoint.com/sites/OUSHF-O-PATXJSeksjonmolekylrpatologi/Shared%20Documents/5_IKT/Bioinformatikk/PowerBI/MolStat/Hemato/resultater.csv"
				            ),
				            [
				                Delimiter = ";",
				                Columns = 12,
				                Encoding = 65001,
				                QuoteStyle = QuoteStyle.None
				            ]
				        ),
				
				    #"Forfremmede overskrifter" =
				        Table.PromoteHeaders(
				            Kilde,
				            [PromoteAllScalars = true]
				        ),
				
				    #"Endret kolonnetype" =
				        Table.TransformColumnTypes(
				            #"Forfremmede overskrifter",
				            {
				                {"Materiale", type text},
				                {"Analyse", type text},
				                {"Nukleinsyre", type text},
				                {"Rapportgruppe", type text},
				                {"Tidspunkt.prøvetaking", type datetime},
				                {"Tidspunkt.opprettet", type datetime},
				                {"Tidspunkt.analysebestilling", type datetime},
				                {"Tidspunkt.analyseresultat", type datetime},
				                {"Tidspunkt.godkjenning", type datetime},
				                {"Ekstraksjon.analysebestilling", type datetime},
				                {"Ekstraksjon.ferdig", type datetime},
				                {"Svarfrist", Int64.Type}
				            },
				            "no"
				        )
				in
				    #"Endret kolonnetype"

	annotation PBI_NavigationStepName = Navigasjon

	annotation PBI_ResultType = Table
